name: 'Amplify PR Preview'
on:
  pull_request:
    branches:
      - master
    types: [review_requested]

jobs:
  deploy:
    if: contains(github.event.pull_request.labels.*.name, 'Ready for review')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: set branchname env
      id: setenvname
      run: |
        # use GITHUB_HEAD_REF that is set to PR source branch
        echo "##[set-output name=setbranchname;]$(echo ${GITHUB_HEAD_REF} | cut -c-10)"

    - name: deploy PR preview with another(new) backend env
      if: contains(github.event.pull_request.labels.*.name, 'newbackendenv')
      uses: yinlinchen/amplify-preview-actions@master
      with:
        branch_name: ${{ steps.setenvname.outputs.setbranchname }}
        amplify_command: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AmplifyAppId: ${{ secrets.AmplifyAppId }}
        AWS_REGION: 'us-east-1'
        BackendEnvARN: ${{ secrets.NewBackendEnvARN }}

    - name: deploy PR preview with current backend env
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'newbackendenv') }}
      uses: yinlinchen/amplify-preview-actions@master
      with:
        branch_name: ${{ steps.setenvname.outputs.setbranchname }}
        amplify_command: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AmplifyAppId: ${{ secrets.AmplifyAppId }}
        AWS_REGION: 'us-east-1'
        BackendEnvARN: ${{ secrets.BackendEnvARN }}
